id: A1484C744
title: 'Divine Music: Words of Encouragement for the Authentic Path'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:29:13.689540
  last_modified_at: 2022-03-01 00:29:13.689542
