id: A1484C744
title: Prayer to Invoke the Wisdom Mind of the Gentle Protector Sakya Paṇḍita
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:29:13.695334
  last_modified_at: 2022-03-01 00:29:13.695338
