id: A1484C744
title: Concise Middle Way Aspiration
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:29:13.686976
  last_modified_at: 2022-03-01 00:29:13.686979
