id: A1484C744
title: A Song of Prayer to Jamyang Loter Wangpo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:29:13.685018
  last_modified_at: 2022-03-01 00:29:13.685026
