id: A1484C744
title: Middle Way Aspiration
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:29:13.692590
  last_modified_at: 2022-03-01 00:29:13.692593
